
var sDefaultCssClass="plain";var hashPrintCssClasses={'body':'','rte':'','plain':'','template':'','clearformat':'','plainlink':'','noitems':'','plainsmall':'','plainlarge':'','plainfixedwidth':'','heading1':'','heading2':'','galleryinfo':'','zoomalt':'','imagelink':'','areaheader':'','areafooter':'','gallery-cutOff':'','copyright':'','manualgalnav':'','manualgalnavcurr':'','alert':'','content_area':'','button':'','mlistfield':'','fb_perm_link_popup':'','siteTitle':'','pageTitle':'','newspagetitle':'','newsdate':'','newstitle':'','newsbody':'','print_content_holder':''};var arrContentAreas=new Array();arrContentAreas[0]="AREA__MAIN_CONTENT_COL1";arrContentAreas[1]="AREA__MAIN_CONTENT_COL2";arrContentAreas[2]="AREA__MAIN_CONTENT_COL3";arrContentAreas[3]="AREA__NEWS_AREA";var Content={};function LoadContent(){if(window.opener&&!window.opener.closed){for(i=0;i<arrContentAreas.length;i++){if(window.opener.document.getElementById(arrContentAreas[i])){var oContentArea=window.opener.document.getElementById(arrContentAreas[i]);var bIncludeChildren=true;var oContentAreaCloned=oContentArea.cloneNode(bIncludeChildren);var arrScriptNodes=oContentAreaCloned.getElementsByTagName("SCRIPT");for(j=0;j<arrScriptNodes.length;j++){if(arrScriptNodes[j].innerHTML!=''){arrScriptNodes[j].innerHTML='';}}
var arrImgNodes=oContentAreaCloned.getElementsByTagName("IMG");for(j=0;j<arrImgNodes.length;j++){if((arrImgNodes[j].src.indexOf('../../../img./')==0)&&(arrImgNodes[j].src.indexOf('.img')>0)){if(arrImgNodes[j].src.indexOf('?')==-1){delim='../../../0101.nccdn.net/default.htm';}else{delim='&';}
arrImgNodes[j].src=arrImgNodes[j].src+delim+"print_mode=1";}}
var arrAllNodes=oContentAreaCloned.getElementsByTagName("*");for(var j=0;j<arrAllNodes.length;j++){var oNode=arrAllNodes[j];if(oNode.style.visibility=='hidden'||(oNode.className=='slide'&&oNode.style.visibility!='visible')){oNode.style.display='none';}}
Content[arrContentAreas[i]]=oContentAreaCloned.innerHTML;}}}}
function ReplaceDesignSpecificCssClasses(){var arrNodes=document.body.getElementsByTagName('*');for(var i=0;i<arrNodes.length;i++){if((arrNodes[i].className)&&(typeof(hashPrintCssClasses[arrNodes[i].className])=='undefined')){arrNodes[i].className=sDefaultCssClass;}}
return 0;}
function OnLoadActions(){return 0;}
function CgiParams(name,url_str,delimiter){delimiter=(delimiter)?delimiter:'&';var temp,cur_len,pattern=/\+/g;url_str=url_str.substring(url_str.indexOf('?')+1);var pairs=url_str.split(delimiter);for(var i=0;i<pairs.length;i++){if(pairs[i].indexOf(name)==0){return pairs[i].split('=')[1].replace(pattern,'  ');}}
return-1;}