
function SKResizeContainer(id,options)
{var container=document.getElementById(id);SKResizeContainerObject(container,options);}
function SKResizeContainerObject(container,options)
{if(typeof options=='undefined'){options={};}
if(typeof options.ResizeIfShorter=='undefined'){options.ResizeIfShorter=1;}
if(typeof options.ResizeAlways=='undefined'){options.ResizeAlways=0;}
var children=container.childNodes;var children_width=0;for(var i=0;i<children.length;i++){var w=parseInt(children[i].offsetWidth);if(!isNaN(w)){var margin_left=parseInt(children[i].style.marginLeft);var margin_right=parseInt(children[i].style.marginRight);var padding_left=parseInt(children[i].style.paddingLeft);var padding_right=parseInt(children[i].style.paddingRight);if(isNaN(margin_left)){margin_left=0;}
if(isNaN(margin_right)){margin_right=0;}
if(isNaN(padding_left)){padding_left=0;}
if(isNaN(padding_right)){padding_right=0;}
children_width+=w+margin_left+margin_right+padding_left+padding_right;}}
if(options.ResizeAlways==1||(options.ResizeIfShorter==1&&parseInt(container.offsetWidth)<children_width)){container.style.width=children_width+"px";}}


SK.Actions.SelectiveMenu={openForEditing:function(fh,obj){var selective_menu=SK.Singletons.env.get('selective_menu');SK.Actions.openForEditing(fh,obj,{selective_nav_area_node_id:selective_menu!=''?selective_menu.parent_id:''});},isSelectiveAreaEditEnabled:function(fh,obj){return SK.Singletons.env.get('selective_menu')=='';},del:function(fh,obj){var selective_menu=SK.Singletons.env.get('selective_menu');if(selective_menu==""){return;}
SK.Actions.SelectiveMenu.delConfirm(selective_menu.name,selective_menu.node_id,selective_menu.parent_id,$defined(selective_menu.nav_menu_node_id_prop_name)?selective_menu.nav_menu_node_id_prop_name:"");fh.notifyCallbackFinished(obj);},delConfirm:function(menu_name,node_id,parent_id,nav_menu_node_id_prop_name){var all_pages_button={caption:'Remove permanently from all pages',callback:function(){SK.Actions.SelectiveMenu.execDelete('SelectiveMenuForm'+node_id,menu_name,node_id,parent_id,0,nav_menu_node_id_prop_name);}};var this_page_button={caption:'Delete',callback:function(){SK.Actions.SelectiveMenu.execDelete('SelectiveMenuForm'+node_id,menu_name,node_id,parent_id,1,nav_menu_node_id_prop_name);}};var cancel_button={caption:'Cancel',callback:null}
var buttons=new Array(this_page_button,cancel_button,all_pages_button);new SK.UI.MessageBox("Are you sure you want to delete the per-page navigation <b>{menu_name}</b> from the current page?".substitute({menu_name:menu_name}),buttons);},execDelete:function(form_name,menu_name,node_id,parent_id,remove_tmp,nav_menu_node_id_prop_name){var msg="You are about to delete the per-page navigation {menu_name} permanently from your site.\r\nThis action is not reversible.\r\nAre you sure you want to proceed?".substitute({menu_name:menu_name});var form=document.forms[form_name];form.do_nm_remove.value="go";form.nm_node_id.value=node_id;form.parent_id.value=parent_id;form.nav_menu_node_id_prop_name.value=nav_menu_node_id_prop_name;if(remove_tmp==0){SKConfirm(msg,function(){form.remove_tmp.value=remove_tmp;SK.Actions.Common.displayProgress("Permanently deleting item...",function(){form.submit();});});}else{SK.Actions.Common.displayProgress("Deleting item...",function(){form.submit();});}}};


Fx.Elements=new Class({Extends:Fx.CSS,initialize:function(elements,options){this.elements=this.subject=$$(elements);this.parent(options);},compute:function(from,to,delta){var now={};for(var i in from){var iFrom=from[i],iTo=to[i],iNow=now[i]={};for(var p in iFrom)iNow[p]=this.parent(iFrom[p],iTo[p],delta);}
return now;},set:function(now){for(var i in now){var iNow=now[i];for(var p in iNow)this.render(this.elements[i],p,iNow[p],this.options.unit);}
return this;},start:function(obj){if(!this.check(arguments.callee,obj))return this;var from={},to={};for(var i in obj){var iProps=obj[i],iFrom=from[i]={},iTo=to[i]={};for(var p in iProps){var parsed=this.prepare(this.elements[i],p,iProps[p]);iFrom[p]=parsed.from;iTo[p]=parsed.to;}}
return this.parent(from,to);}});


var Accordion=new Class({Extends:Fx.Elements,options:{display:0,show:false,height:true,width:false,opacity:true,fixedHeight:false,fixedWidth:false,wait:false,alwaysHide:false},initialize:function(){var params=Array.link(arguments,{'container':Element.type,'options':Object.type,'togglers':$defined,'elements':$defined});this.parent(params.elements,params.options);this.togglers=$$(params.togglers);this.container=$(params.container);this.previous=-1;if(this.options.alwaysHide)this.options.wait=true;if($chk(this.options.show)){this.options.display=false;this.previous=this.options.show;}
if(this.options.start){this.options.display=false;this.options.show=false;}
this.effects={};if(this.options.opacity)this.effects.opacity='fullOpacity';if(this.options.width)this.effects.width=this.options.fixedWidth?'fullWidth':'offsetWidth';if(this.options.height)this.effects.height=this.options.fixedHeight?'fullHeight':'scrollHeight';for(var i=0,l=this.togglers.length;i<l;i++)this.addSection(this.togglers[i],this.elements[i]);this.elements.each(function(el,i){if(this.options.show===i){this.fireEvent('active',[this.togglers[i],el]);}else{for(var fx in this.effects)el.setStyle(fx,0);}},this);if($chk(this.options.display))this.display(this.options.display);},addSection:function(toggler,element,pos){toggler=$(toggler);element=$(element);var test=this.togglers.contains(toggler);var len=this.togglers.length;this.togglers.include(toggler);this.elements.include(element);if(len&&(!test||pos)){pos=$pick(pos,len-1);toggler.inject(this.togglers[pos],'before');element.inject(toggler,'after');}else if(this.container&&!test){toggler.inject(this.container);element.inject(this.container);}
var idx=this.togglers.indexOf(toggler);toggler.addEvent('click',this.display.bind(this,idx));if(this.options.height)element.setStyles({'padding-top':0,'border-top':'none','padding-bottom':0,'border-bottom':'none'});if(this.options.width)element.setStyles({'padding-left':0,'border-left':'none','padding-right':0,'border-right':'none'});element.fullOpacity=1;if(this.options.fixedWidth)element.fullWidth=this.options.fixedWidth;if(this.options.fixedHeight)element.fullHeight=this.options.fixedHeight;element.setStyle('overflow','hidden');if(!test){for(var fx in this.effects)element.setStyle(fx,0);}
return this;},display:function(index){index=($type(index)=='element')?this.elements.indexOf(index):index;if((this.timer&&this.options.wait)||(index===this.previous&&!this.options.alwaysHide))return this;this.previous=index;var obj={};this.elements.each(function(el,i){obj[i]={};var hide=(i!=index)||(this.options.alwaysHide&&(el.offsetHeight>0));this.fireEvent(hide?'background':'active',[this.togglers[i],el]);for(var fx in this.effects)obj[i][fx]=hide?0:el[this.effects[fx]];},this);return this.start(obj);}});


Fx.Slide=new Class({Extends:Fx,options:{mode:'vertical'},initialize:function(element,options){this.addEvent('complete',function(){this.open=(this.wrapper['offset'+this.layout.capitalize()]!=0);if(this.open&&Browser.Engine.webkit419)this.element.dispose().inject(this.wrapper);},true);this.element=this.subject=$(element);this.parent(options);var wrapper=this.element.retrieve('wrapper');this.wrapper=wrapper||new Element('div',{styles:$extend(this.element.getStyles('margin','position'),{'overflow':'hidden'})}).wraps(this.element);this.element.store('wrapper',this.wrapper).setStyle('margin',0);this.now=[];this.open=true;},vertical:function(){this.margin='margin-top';this.layout='height';this.offset=this.element.offsetHeight;},horizontal:function(){this.margin='margin-left';this.layout='width';this.offset=this.element.offsetWidth;},set:function(now){this.element.setStyle(this.margin,now[0]);this.wrapper.setStyle(this.layout,now[1]);return this;},compute:function(from,to,delta){var now=[];var x=2;x.times(function(i){now[i]=Fx.compute(from[i],to[i],delta);});return now;},start:function(how,mode){if(!this.check(arguments.callee,how,mode))return this;this[mode||this.options.mode]();var margin=this.element.getStyle(this.margin).toInt();var layout=this.wrapper.getStyle(this.layout).toInt();var caseIn=[[margin,layout],[0,this.offset]];var caseOut=[[margin,layout],[-this.offset,0]];var start;switch(how){case'in':start=caseIn;break;case'out':start=caseOut;break;case'toggle':start=(this.wrapper['offset'+this.layout.capitalize()]==0)?caseIn:caseOut;}
return this.parent(start[0],start[1]);},slideIn:function(mode){return this.start('in',mode);},slideOut:function(mode){return this.start('out',mode);},hide:function(mode){this[mode||this.options.mode]();this.open=false;return this.set([-this.offset,0]);},show:function(mode){this[mode||this.options.mode]();this.open=true;return this.set([0,this.offset]);},toggle:function(mode){return this.start('toggle',mode);}});Element.Properties.slide={set:function(options){var slide=this.retrieve('slide');if(slide)slide.cancel();return this.eliminate('slide').store('slide:options',$extend({link:'cancel'},options));},get:function(options){if(options||!this.retrieve('slide')){if(options||!this.retrieve('slide:options'))this.set('slide',options);this.store('slide',new Fx.Slide(this,this.retrieve('slide:options')));}
return this.retrieve('slide');}};Element.implement({slide:function(how,mode){how=how||'toggle';var slide=this.get('slide'),toggle;switch(how){case'hide':slide.hide(mode);break;case'show':slide.show(mode);break;case'toggle':var flag=this.retrieve('slide:flag',slide.open);slide[(flag)?'slideOut':'slideIn'](mode);this.store('slide:flag',!flag);toggle=true;break;default:slide.start(how,mode);}
if(!toggle)this.eliminate('slide:flag');return this;}});


Element.implement({isDisplayed:function(){return this.getStyle('display')!='none';},toggle:function(){return this[this.isDisplayed()?'hide':'show']();},hide:function(){var d;try{d=this.getStyle('display');}catch(e){}
return this.store('originalDisplay',d||'block').setStyle('display','none');},show:function(display){return this.setStyle('display',display||this.retrieve('originalDisplay')||'block');}});


var HORIZONTAL=0;var VERTICAL=1;var STRIPE_BELOW_MAIN_ITEMS=0;var DROPDOWN_BELOW_MAIN_ITEMS=1;var DROPDOWN_BETWEEN_ITEMS=2;var DROPDOWN_AT_RIGHT=3;var SELECTED_CLASS_NAME='sel';var CURRENT_CLASS_NAME='cur';var CURRENT_SUBITEM_CLASS_NAME='curSub';var FIRST_BUTTON_CLASS_NAME=' fmBtnFst ';var LAST_BUTTON_CLASS_NAME=' fmBtnLst ';


var SKSliderTimeouts={};var SKSliderOptions={};var SKSlider={};SKSlider.timer={};var SKSliders={};SKSliderOptions.DEFAULT={window_width:160,width:500,step:10};var SKTwoWaySlider=new Class({initialize:function(element,slider_name,props){this.element=element;this.window_width=(props&&props.window_width)?props.window_width:SKSliderOptions.DEFAULT.window_width;this.timeout_wait=(typeof props.timeout_wait!='undefined')?props.timeout_wait:SKMenuOptions.slider.DEFAULT.wait;this.width=props.org_width;this.step=(props&&props.step>0)?props.step:3;this.name=slider_name;this.Init();},Init:function(){this.height=$(this.element).getStyle('height').replace("px","");this.slide_offset=this.width-this.window_width;this.left_offset=0;this.slide_start=0;this.slide_end=this.slide_start+this.slide_offset;this.slide_pos=this.slide_start;this.user_direction=1;this.finished=false;this.right_cycle_finished=false;this.timer;this.direction=1;this.count=10;this.counter=0;},ResetSlide:function(){if(this.timer)clearTimeout(this.timer);this.height=$(this.element).getStyle('height').replace("px","");this.slide_offset=this.width-this.window_width;this.left_offset=0;this.slide_start=0;this.slide_end=this.slide_start+this.slide_offset;this.slide_pos=this.slide_start;this.finished=false;this.right_cycle_finished=false;this.counter=0;this.direction=1;this.ClipLayer();this.SetPositon();},ClipLayer:function(){var right=this.slide_pos+this.window_width;var left=this.slide_pos;var clip_str="rect("+0+"px "+right+"px "+this.height+"px "+left+"px)";this.element.style.clip=clip_str;},SetPositon:function(){var offset=(-1)*this.left_offset;this.element.style.left=offset+"px";},Slide:function(direction){if(typeof direction=='unedefined'){direction=this.direction;}
this.user_direction=direction;if(this.user_direction==-1){this.right_cycle_finished=false;this.direction=-1;}
if(this.user_direction==1&&this.right_cycle_finished==true){return;}
this.SlideByStep();if(this.user_direction==-1){this.direction=1;}},SlideByStep:function(){var direction=this.direction;var new_pos=this.slide_pos+this.step*direction;if(this.user_direction==-1&&this.slide_pos==this.slide_start&&new_pos<this.slide_start){this.finished=true;return;}else{this.finished=false;}
if(new_pos<this.slide_start){if(this.user_direction==1){this.right_cycle_finished=true;}
else
{this.right_cycle_finished=false;}
return;}
if(new_pos>this.slide_end&&this.user_direction==1){if(this.counter<this.count){this.counter++;}
else{this.counter=0;this.ChangeDirection();}
return;}
this.left_offset+=this.step*direction;this.slide_pos=new_pos;this.ClipLayer();this.SetPositon();},ChangeDirection:function(){this.direction=(-1)*this.direction;},SetWindowWidth:function(new_window_width){if(new_window_width>=0){this.window_width=new_window_width;}},SetTimeoutWait:function(new_timeout_wait){if(new_timeout_wait>=0){this.timeout_wait=new_timeout_wait;}},SetStep:function(new_step){if(new_step>=0){this.step=step;}},SetOrgWidth:function(new_org_width){if(new_org_width>=0){this.width=new_org_width;}},SetName:function(new_name){if(new_name>=0){this.name=new_name;}}});SKEffectsFactory.Slider={};SKEffectsFactory.Slider.timer={};SKEffectsFactory.Slider.Start=function(slider){slider.Slide(2);var timeout_wait=slider.timeout_wait;if(SKEffectsFactory.Slider.timer[slider.name]){clearTimeout(SKEffectsFactory.Slider.timer[slider.name]);}
SKEffectsFactory.Slider.timer[slider.name]=setTimeout(function(){SKEffectsFactory.Slider.Start(slider);},timeout_wait);}
SKEffectsFactory.Slider.TwoWaySlide=function(slider,direction){if(typeof slider=="undefined"||slider==null||slider.window_width>=slider.width)return;slider.Slide(direction);var timeout_wait=slider.timeout_wait;if(slider.timer)clearTimeout(slider.timer);if(!slider.finished){slider.timer=setTimeout(function(){SKEffectsFactory.Slider.TwoWaySlide(slider,direction);},timeout_wait);}}
SKSlider.Start=function(slider){slider.Slide(2);var timeout_wait=slider.timeout_wait;if(SKSlider.timer[slider.name]){clearTimeout(SKSlider.timer[slider.name]);}
SKSlider.timer[slider.name]=setTimeout(function(){SKSlider.Start(slider);},timeout_wait);}
SKSlider.TwoWaySlide=function(slider,direction){if(typeof slider=="string"&&eval("typeof "+slider)!='undefined')slider=eval(slider);if(typeof slider=="undefined"||slider==null||slider.window_width>=slider.width)return;slider.Slide(direction);var timeout_wait=slider.timeout_wait;if(slider.timer)clearTimeout(slider.timer);if(!slider.finished){slider.timer=setTimeout(function(){SKSlider.TwoWaySlide(slider,direction);},timeout_wait);}}


var SKMenuOptions={};SKMenuOptions.holders={};SKMenuOptions.holders.DEFAULT={submenu:[{"tagName":"div","class":"effects_wrapper"},{"tagName":"div","style":{"overflow":"hidden"}},{"tagName":"div","class":"effects_holder","style":{"visibility":"hidden","position":"absolute"}},{"tagName":"div","class":"subNav"}],item:[]}
SKMenuOptions.holders.NOANIMATION={submenu:[{"tagName":"div","class":"effects_wrapper"},{"tagName":"div","style":{"overflow":"visible"}},{"tagName":"div","class":"effects_holder","style":{"visibility":"hidden"}},{"tagName":"div","class":"subNav"}],item:[]}
SKMenuOptions.events={};SKMenuOptions.events.DEFAULT={"mouseover":"show","mouseout":"hide"}
SKMenuOptions.events.CLICK={"mouseover":"show","mouseout":"hide","click":"click"}
SKMenuOptions.timeouts={};SKMenuOptions.timeouts.DEFAULT={"show":0,"hide":50,"hide_no_sub":50,"show_sub":0,"hide_sub":0,"rollover_next":50,"click":0};SKMenuOptions.dimensions={};SKMenuOptions.dimensions.DEFAULT={"first_level":{"visible_window_width":140},"subitems":{"visible_window_width":160,"stretch_increment":100},"menu_padding":20,"dft_si_height":15,"wce_icon_width":10};SKMenuOptions.slider={};SKMenuOptions.slider.DEFAULT={"start":300,"end":300,"wait":50,"step":3}
SKMenuOptions.callbacks={};SKMenuOptions.callbacks.DEFAULT={"after_traverse":function(menu_item){var submenu_layout=main_menu.submenu_layout;var container_id="container_menu";SKUtils.PrepareMenuContainer(container_id,submenu_layout);SKUtils.RemoveElement(container_id);},"before_traverse":function(menu_item){}}
SKMenuOptions.behaviors={};SKMenuOptions.behaviors.DEFAULT={"onhide":function(menu_item){var parent_item=menu_item.ParentMenuItem();if(typeof parent_item!='undefined'){menu_item.SubSynchronized(true,1);var slider=SKSliders[menu_item.element.id+"_slider"];if(slider)
window.setTimeout(function(){SKSlider.TwoWaySlide(slider,-1);},200);return;}else{SKEffectsFactory.SubSynchronization[menu_item.element.id]+=1;menu_item.Synchronized(false);}
if(typeof menu_item.SubMenu!='undefined'){menu_item.HideAnimation();}
menu_item.UnsetSelected();},"onshow":function(menu_item){var parent_item=menu_item.ParentMenuItem();if(typeof parent_item!='undefined'){menu_item.SubSynchronized(true);var slider=SKSliders[menu_item.element.id+"_slider"];if(slider)
window.setTimeout(function(){SKSlider.TwoWaySlide(slider,1);},200);return;}else{if(!menu_item.Synchronized()){menu_item.Synchronized(true);}
else{return;}}
var id=menu_item.element.id;menu_item.HideSiblings();menu_item.SetSelected();menu_item.root_obj.SetSubmenuPosition(menu_item);menu_item.root_obj.ResetSubitems(menu_item);menu_item.ShowAnimation();menu_item.Synchronized(true);}};SKMenuOptions.behaviors.CLICK={"onhide":function(menu_item){var parent_item=menu_item.ParentMenuItem();if(typeof parent_item!='undefined'){menu_item.SubSynchronized(true,1);var slider=SKSliders[menu_item.element.id+"_slider"];if(slider)
window.setTimeout(function(){SKSlider.TwoWaySlide(slider,-1);},200);return;}else{SKEffectsFactory.SubSynchronization[menu_item.element.id]+=1;menu_item.Synchronized(false);}
var menu_obj=menu_item.SubMenu();var holder;if(menu_obj&&typeof menu_obj!='undefined')
holder=menu_obj.GetHolder();if(menu_item.HasLock(SELECTED_CLASS_NAME))
return;menu_item.UnsetSelected();},"onshow":function(menu_item){var parent_item=menu_item.ParentMenuItem();if(typeof parent_item!='undefined'){menu_item.SubSynchronized(true);var slider=SKSliders[menu_item.element.id+"_slider"];if(slider)
window.setTimeout(function(){SKSlider.TwoWaySlide(slider,1);},200);return;}else{if(!menu_item.Synchronized()){menu_item.Synchronized(true);}else{return;}}
menu_item.HideSiblings();menu_item.SetSelected();menu_item.root_obj.SetSubmenuPosition(menu_item);menu_item.Synchronized(true);},"onclick":function(menu_item,disabled_check_for_link){var link_obj=SKElement.GetFirstElementByTag(menu_item.element,'A');if(typeof disabled_check_for_link=='undfined'||!disabled_check_for_link)
if(link_obj.href.indexOf('javascript:void(null)')==-1)
return;var menu_obj;if($(menu_item.sub_menu_id)){menu_obj=new SKMenu($(menu_item.sub_menu_id),menu_item.root_obj);}else{menu_obj=menu_item.SubMenu();}
if(!menu_obj||typeof menu_obj=='undefined')
return;if(menu_item.HasLock(SELECTED_CLASS_NAME)){menu_item.RemoveLock(SELECTED_CLASS_NAME);menu_item.HideAnimation();}else{menu_item.SetLock(SELECTED_CLASS_NAME);menu_item.ShowAnimation();}}};var SKAnimations={};SKAnimations.COMMON={"options":{"onComplete":function(obj){var fx=(obj)?obj:this;if(fx.element&&fx.element.getStyle('visibility')=='hidden')
fx.element.setStyle('visibility','visible');if(fx.element&&fx.element.getStyle('position')=='absolute')
fx.element.setStyle('position','static');}}}
SKAnimations.DEFAULT={"effect":function(item,options){var sub_menu=item.SubMenu();var holder=sub_menu.GetHolder();return new Fx.Tween(holder,options);},"show":function(fx){fx.element.parentNode.setStyle('display','block');},"hide":function(fx){fx.element.parentNode.setStyle('display','none');},"reset":function(fx){fx.element.parentNode.setStyle('display','none');fx.element.setStyle('visibility','visible');fx.element.parentNode.setStyle('position','static');}};SKAnimations.SLIDE={"visible":1,"out":0,"undef":1,"effect":function(item,options){var sub_menu=item.SubMenu();var holder=sub_menu.GetHolder();var children=holder.getChildren();var sub_nav=null;for(var i=0;i<children.length;i++)
if(children[i].className.indexOf('subNav')!=-1)
sub_nav=children[i];if(sub_nav){holder.parentNode.setStyles({'margin':sub_nav.getStyle('margin')});sub_nav.setStyle('margin','0px');}
holder.store('wrapper',holder.parentNode)
return new Fx.Slide(holder,options);},"show":function(fx){fx.element.set('undef',0);fx.element.set('visible',1);fx.element.set('out',0);fx.cancel();fx.slideIn();},"hide":function(fx){fx.element.set('undef',0);fx.element.set('visible',0);fx.element.set('out',1);fx.cancel();fx.slideOut();},"reset":function(fx){fx.cancel();fx.slideOut();fx.element.set('visible',0);},"options":{"mode":'vertical',"transition":Fx.Transitions.Cubic.easeOut,"onStart":function(){if(this.to[0]>=0){var parent=this.element.getParent();var margin=parent.retrieve('skanimations:slide:margin');if(margin){parent.setStyle('margin',margin);}}},"onComplete":function(){if(this.to[0]<0){if(this.element.get('out')==1){this.element.set('visible',0);var parent=this.element.getParent();if(!parent.retrieve('skanimations:slide:margin')){parent.store('skanimations:slide:margin',parent.getStyle('margin'));}
parent.setStyle('margin',0);}
SKAnimations.COMMON.options.onComplete(this);}else{if(this.element.get('undef')==0){this.element.set('visible',1);}}}}};SKAnimations.SLIDE_HORIZONTAL={"effect":SKAnimations.SLIDE.effect,"show":SKAnimations.SLIDE.show,"hide":SKAnimations.SLIDE.hide,"reset":SKAnimations.SLIDE.reset,"options":{"mode":'horizontal',"transition":Fx.Transitions.Cubic.easeOut,"onComplete":function(){SKAnimations.COMMON.options.onComplete(this);}}};SKAnimations.SLIDE_DOWN={"effect":SKAnimations.SLIDE.effect,"show":SKAnimations.SLIDE.show,"hide":SKAnimations.SLIDE.hide,"reset":SKAnimations.SLIDE.reset,"options":{"onComplete":function(){SKAnimations.SLIDE.options.onComplete.run([],this);this.element.setStyle('height','auto');this.element.getParent().setStyle('height','auto');}}};SKAnimations.FADE={"effect":function(item,options){var sub_menu=item.SubMenu();var holder=sub_menu.GetHolder();return new Fx.Tween(holder,options);},"show":function(fx){fx.cancel();fx.start('opacity',1);},"hide":function(fx){fx.cancel();fx.start('opacity',0);},"reset":function(fx){fx.cancel();fx.start('opacity',[0,0]);},"options":{"transition":Fx.Transitions.Cubic.easeOut,"onStart":function(){if(this.to[0].value==1)
this.element.parentNode.setStyle('display','block')},"onComplete":function(){SKAnimations.COMMON.options.onComplete(this);if(this.to[0].value==0)
this.element.parentNode.setStyle('display','none');}}};SKMenuOptions.element={};SKMenuOptions.helpers={};var SKDesigns={};SKDesigns.Default={"behavior_type":SKMenuOptions.behaviors.DEFAULT,"holders":SKMenuOptions.holders.DEFAULT,"dimensions":SKMenuOptions.dimensions.DEFAULT,"slider":SKMenuOptions.slider.DEFAULT,"timeout":SKMenuOptions.timeouts.DEFAULT,"callbacks":SKMenuOptions.callbacks.DEFAULT,"scroll":false}


var hashFirstElementMap=[];var ITEMS_CACHE=[];var ITEMS_FX={};var ITEMS_LOCKS={};function SKElement(){};function SKUtils(){};var SKMenu=new Class({Extends:SKElement,initialize:function(element,root_obj){this.element=element;if(typeof root_obj!='undefined'){this.root_obj=root_obj;}
this.width=0;this.height=0;this.icon_width=this.root_obj.icon_width;},Items:function(){if(typeof this.menu_items=='undefined'){this.menu_items=[];var list_items=new Array();var element=this.element;if(!element||typeof element.tagName=='undefined')return;if(element.tagName.toUpperCase()=='UL'){list_items=SKElement.GetChildrenByTag(element,'LI');}
if(element.tagName.toUpperCase()=='TABLE'){var oTBody=null;for(var i=0;i<element.childNodes.length;i++)
if(element.childNodes[i].tagName&&element.childNodes[i].tagName.toUpperCase()=='TBODY')
oTBody=element.childNodes[i];var arrTableRows=oTBody.childNodes;for(var i=0;i<arrTableRows.length;i++){var arrTableCells=SKElement.GetChildrenByTag(arrTableRows[i],'TD');arrTableCells.each(function(item,index){if(SKElement.ContainsElementOfClass(item,'menu_contents'))list_items.push(item);});}}
for(var i=0;i<list_items.length;i++){var internal_link=$(list_items[i]).retrieve('internal_link');var menu_item=new SKMenuItem(list_items[i],{parent_id:this.element.id,position:i,root_obj:this.root_obj,internal_link:internal_link});this.menu_items.push(menu_item);}}
return this.menu_items;},ParentMenu:function(){var parent=SKElement.ParentListElement(this.element);return new SKMenu(parent,this.root_obj);},ParentMenuItem:function(){var parent_item;var parent_element=SKElement.GetParentByTag(this.element,"LI");if(typeof parent_element=='undefined')
parent_element=SKElement.GetParentByTag(this.element,"TD");if(typeof parent_element!='undefined')
parent_item=new SKMenuItem($(parent_element),{root_obj:this.root_obj});return parent_item;},CalculatePositionRelativeToMainMenu:function(orientation,submenu_layout){var bTableLayout=0;var effects_wrapper=SKElement.GetParentByClassName($(this.element),'effects_wrapper');if(typeof effects_wrapper=='undefined')return;var effects_holder=SKElement.GetParentByClassName($(this.element),'effects_holder');if(typeof effects_holder=='undefined')return;var submenu_width=effects_holder.getStyle("width");if(submenu_width&&typeof submenu_width!='undefined'&&submenu_width!='0px'&&submenu_width!='auto'){submenu_width=SKUtils.SizeToNumber(submenu_width);}else{if(effects_holder.parentNode.getStyle("display")=='none'){effects_holder.parentNode.setStyle('display','block');submenu_width=effects_holder.offsetWidth;effects_holder.parentNode.setStyle('display','none');}else if(effects_holder.getStyle("display")=='none'){effects_wrapper.style.left='';effects_wrapper.style.position='relative';effects_wrapper.style.position='absolute';effects_wrapper.addClass('tmp');effects_holder.setStyle('display','block');submenu_width=effects_holder.offsetWidth;effects_holder.setStyle('display','none');effects_wrapper.removeClass('tmp');}else{submenu_width=effects_holder.offsetWidth;}}
var main_menu=SKElement.GetParentByTag($(this.element),'UL');var main_menu_wrapper=SKElement.GetParentByTag(main_menu,'DIV');if(typeof main_menu=='undefined'){main_menu=SKElement.GetParentByTag($(this.element),'TABLE');main_menu_wrapper=SKElement.GetParentByTag(main_menu,'TD');bTableLayout=1;}
var main_menu_width=this.root_obj.menu_width;if(main_menu.offsetWidth>main_menu_width)
main_menu_width=main_menu.offsetWidth;if(main_menu_wrapper.offsetWidth>main_menu_width)
main_menu_width=main_menu_wrapper.offsetWidth;var left_offset=null;var layer=SKElement.GetParentByClassName($(this.element),'effects_wrapper');layer.style.left='';if(!bTableLayout){var main_menu_list_item=SKElement.GetParentByTag($(this.element),'LI');var main_menu_left_x=SKElement.GetFirstElementByTag(main_menu,'LI').offsetLeft;var main_menu_right_x=main_menu_width;var menu_item_left_x=main_menu_list_item.offsetLeft-main_menu_left_x;if(main_menu_right_x-menu_item_left_x>submenu_width){left_offset=0;}else{left_offset=main_menu_right_x-submenu_width-menu_item_left_x;}}
if(bTableLayout){var main_menu_table_cell=SKElement.GetParentByTag($(this.element),'TD');var menu_wrapper_left=main_menu_wrapper.offsetLeft;var menu_left=main_menu.offsetLeft;var menu_item_width=main_menu_table_cell.offsetWidth;var menu_item_left=main_menu_table_cell.offsetLeft;if(document.all){var menu_wrapper_border=SKElement.GetBorderWidth(main_menu_wrapper);if(menu_wrapper_border)
menu_left+=menu_wrapper_border.left;}
var main_menu_wrapper_right_x=menu_wrapper_left+main_menu_width;var menu_item_left_x=menu_item_left+menu_left;if(main_menu_wrapper_right_x-menu_item_left_x>submenu_width){left_offset=layer.offsetLeft;}else{left_offset=layer.offsetLeft-(submenu_width-(main_menu_wrapper_right_x-menu_item_left_x));if(orientation==HORIZONTAL){var margin_left=(-1)*(submenu_width-(main_menu_wrapper_right_x-menu_item_left_x));$(layer).setStyles({'margin-left':margin_left+"px"});return;}}
if(submenu_layout==DROPDOWN_AT_RIGHT){var margin_top=(-1)*main_menu_table_cell.offsetHeight;var margin_left=main_menu_table_cell.offsetWidth;$(layer).setStyles({'margin-left':margin_left+"px"});$(layer).setStyles({'margin-top':margin_top+"px"});return;}}
$(layer).setStyles({left:left_offset+"px"});},CalculateWidth:function(){var items=this.Items();var padding=(typeof this.padding!='undefined')?this.padding:0;var total_width=0;for(var i=0;i<items.length;i++){var item=items[i];var anchor_element=item.FirstLink();if(typeof anchor_element!='undefined'&&anchor_element!=null){var anchor_width=SKUtils.SizeToNumber($(anchor_element).getStyle("width"));if(typeof anchor_width=='undefined'||anchor_width==null||anchor_width==0)
anchor_width=$(anchor_element).offsetWidth;if(typeof anchor_width!='undefined'&&anchor_width!=null)
total_width+=anchor_width;if(!document.all){var anchor_pl=SKUtils.SizeToNumber($(anchor_element).getStyle("padding-left"));var anchor_pr=SKUtils.SizeToNumber($(anchor_element).getStyle("padding-right"));var anchor_ml=SKUtils.SizeToNumber($(anchor_element).getStyle("margin-left"));var anchor_mr=SKUtils.SizeToNumber($(anchor_element).getStyle("margin-right"));if(typeof anchor_pl!='undefined'&&anchor_pl!=null)total_width+=anchor_pl;if(typeof anchor_pr!='undefined'&&anchor_pr!=null)total_width+=anchor_pr;if(typeof anchor_ml!='undefined'&&anchor_ml!=null)total_width+=anchor_ml;if(typeof anchor_mr!='undefined'&&anchor_mr!=null)total_width+=anchor_mr;}}}
if(total_width>0){total_width+=padding;this.width=total_width;}},StretchAdmin:function(current_layout,icon_width){if(typeof current_layout=='undefined'){current_layout=this.root_obj.submenu_layout;}
if(typeof icon_width=='undefined'){icon_width=this.root_obj.icon_width;}
if(this.root_obj.admin){var items_count=(this.Items()).length;var count=(current_layout==0)?items_count:1;if(this.width==0||typeof this.width=='undefined'||this.width==null){this.width=$(this.element).getStyle("width");this.width=SKUtils.SizeToNumber(this.width)-0;}
this.width+=(count*icon_width);this.SetHolderWidth(this.width);this.SetMenuWidth(this.width);}},SetMenuWidth:function(new_width){var type_str=typeof new_width;if(type_str!="undefined"&&(type_str=="string"||type_str=="number")){$(this.element).setStyles({width:new_width+"px"});}},SetHolderWidth:function(new_width){var holder=this.GetHolder();if(holder){$(holder).setStyles({width:new_width+"px"});}},GetHolder:function(){var holder;var parent_menu=this.ParentMenuItem();if(typeof parent_menu!='undefined'){var parent_id=parent_menu.element.id;var key='#'+parent_id+' .effects_holder';if(!ITEMS_CACHE[key]){ITEMS_CACHE[key]=new Object();var layers=$$(key);if(layers.length>0){holder=layers[0];}
ITEMS_CACHE[key]=holder;}else{holder=ITEMS_CACHE[key];}}
return holder;}});var SKMenuItem=new Class({Extends:SKElement,initialize:function(element,props){this.element=element;this.state_marker_element=null;this.fx=ITEMS_FX[this.element.id];this.locks=new Array();if(ITEMS_LOCKS[this.element.id]){this.locks=ITEMS_LOCKS[this.element.id];}
if(typeof props!='undefined'){this.parent_id=props.parent_id;this.position=props.position;this.root_obj=props.root_obj;if(typeof props.internal_link!='undefined'){this.internal_link=props.internal_link;}}
var first_div=SKElement.GetFirstElementByTag(this.element,'DIV');if(first_div&&first_div.id.indexOf('state_marker')!=-1){this.state_marker_element=first_div;}},SubMenu:function(){var element=this.element;var sub_menu_element=SKElement.GetFirstElementByTag(this.element,"UL");if(typeof sub_menu_element=='undefined')
sub_menu_element=SKElement.GetFirstElementByTag(this.element,"TABLE");if(typeof sub_menu_element!='undefined'){var sub_menu=new SKMenu(sub_menu_element,this.root_obj);return sub_menu;}},Siblings:function(){var parent_menu=this.ParentMenu();var id=this.element.id;var menu_items=parent_menu.Items();var siblings=[];for(var i=0;i<menu_items.length;i++){var sibling=menu_items[i];if(sibling.element.id!=id){siblings.push(sibling);}}
return siblings;},FirstLink:function(){var first_link=SKElement.GetFirstElementByTag(this.element,'A');if(typeof first_link!='undefined'&&first_link.className.indexOf('menu_contents')!=-1||SKElement.ContainsElementOfClass(first_link,'menu_contents'))
{return first_link;}
return null;},GetContentsElement:function(){var contents_element;var id=this.element.id;var key="#"+id+" .menu_contents";if(!ITEMS_CACHE[key]){ITEMS_CACHE[key]=new Object();var layers=$$(key);if(layers.length>0){contents_element=layers[0];}
ITEMS_CACHE[key]=contents_element;}else{contents_element=ITEMS_CACHE[key];}
return contents_element;},ParentMenu:function(){var parent=SKElement.ParentListElement(this.element);return new SKMenu(parent,this.root_obj);},ParentMenuItem:function(){var parent_item;var parent_element=SKElement.GetParentByTag(this.element,"LI");if(typeof parent_element!='undefined'){parent_item=new SKMenuItem($(parent_element),{root_obj:this.root_obj});}
return parent_item;},IsSubItem:function(){var parent_item=this.ParentMenuItem();return(typeof parent_item!='undefined');},SetSelected:function(){if(this.state_marker_element&&typeof this.state_marker_element!='undefined'&&this.state_marker_element.className.indexOf(CURRENT_CLASS_NAME)==-1)
{this.state_marker_element.className=SELECTED_CLASS_NAME;this.RefreshSelected();}
this.FlipImages(0);var slider_name=this.element.id+"_slider";var slider=SKSliders[slider_name];if(slider){window.setTimeout(function(){SKSlider.TwoWaySlide(slider,1);},200);}},UnsetSelected:function(){if(this.state_marker_element&&typeof this.state_marker_element!='undefined'&&this.state_marker_element.className.indexOf(CURRENT_CLASS_NAME)==-1)
{this.state_marker_element.className='';this.RefreshSelected();}
this.FlipImages(1);var slider_name=this.element.id+"_slider";var slider=SKSliders[slider_name];if(slider){window.setTimeout(function(){SKSlider.TwoWaySlide(slider,-1);},200);}},RefreshSelected:function(){},IsSelected:function(){if(this.state_marker_element&&typeof this.state_marker_element!='undefined'&&this.state_marker_element.className.indexOf(SELECTED_CLASS_NAME)!=-1)
return true;return false;},IsCurrent:function(){if(this.state_marker_element&&typeof this.state_marker_element!='undefined'&&this.state_marker_element.className.indexOf(CURRENT_CLASS_NAME)!=-1)
return true;return false;},FlipImages:function(image_index){if(image_index!=0)image_index=1;var other_index=(image_index==0)?1:0;var contents_element=this.GetContentsElement();if(typeof contents_element!='undefined'){var image_elements=SKElement.GetChildrenByTag(contents_element,"IMG",true);if(image_elements.length==2){image_elements[other_index].style.display='none';image_elements[image_index].style.display='';}}},HideSiblings:function(){var siblings=this.Siblings();for(var i=0;i<siblings.length;i++){var sibling=siblings[i];if(sibling.IsSelected()||sibling.IsCurrent()){SKEffectsFactory.ForceHide(sibling);}}},Synchronized:function(flag){var id=this.element.id;var new_value;var old_value=SKEffectsFactory.Synchronization[id];new_value=(typeof flag!='undefined')?flag:((typeof old_value=='undefined')?false:old_value)
SKEffectsFactory.Synchronization[id]=new_value;return new_value;},SynchronizeSiblings:function(flag){var siblings=this.Siblings()
for(var i=0;i<siblings.length;i++){var id=siblings[i].element.id;SKEffectsFactory.Synchronization[id]=false;}},SubSynchronized:function(child,increment){var id;if(typeof child=='undefined'||child==false){return(SKEffectsFactory.SubSynchronization[this.element.id]<2);}
else{var parent_item=this.ParentMenuItem();if(typeof parent_item=='undefined'){return(SKEffectsFactory.SubSynchronization[this.element.id]<2);}
id=parent_item.element.id;}
var old_value=SKEffectsFactory.SubSynchronization[id];var new_value;if(typeof increment!='undefined'){if(typeof old_value=='undefined'){new_value=0;}
new_value+=increment;}
else{new_value=(typeof old_value=='undefined')?1:0;}
SKEffectsFactory.SubSynchronization[id]=new_value;return new_value;},ShowAnimation:function(){if(ITEMS_FX[this.element.id])
this.root_obj.animation_props.show(ITEMS_FX[this.element.id]);},HideAnimation:function(){if(ITEMS_FX[this.element.id])
this.root_obj.animation_props.hide(ITEMS_FX[this.element.id]);},SetLock:function(lock_id){this.locks.push(lock_id);if(!ITEMS_LOCKS[this.element.id])
ITEMS_LOCKS[this.element.id]=new Array();ITEMS_LOCKS[this.element.id].push(lock_id);},HasLock:function(lock_id){for(var i=0;i<this.locks.length;i++)
if(this.locks[i]==lock_id)
return true;return false;},RemoveLock:function(lock_id){for(var i=0;i<this.locks.length;i++)
if(this.locks[i]==lock_id)
delete this.locks[i];if(!ITEMS_LOCKS[this.element.id])
ITEMS_LOCKS[this.element.id]=new Array();ITEMS_LOCKS[this.element.id]=this.locks;}});var SKMainMenu=new Class({Extends:SKMenu,initialize:function(id,props){this.root_id=id;this.element=$(id);this.menu;this.callbacks={};this.slider={};this.scroll=true;this.timeout={};this.width;this.admin=false;this.submenu_layout=0;this.orientation=0;this.style=0;this.icon_width=12;this.animation_props={};this.holders={}
if(typeof props=='undefined'){props={};}
if(typeof props.design!='undefined'){props=SKUtils.MergeHashes(props.design,props);}
this.dimensions={};this.menu_width=$(this.element).getStyle('width');if(typeof this.menu_width=='string'&&this.menu_width!=null){this.menu_width=SKUtils.SizeToNumber(this.menu_width);}
this.InitializeProperty(this.menu_width,props,"menu_width",this.menu_width);if(this.menu_width>0){$(this.element).setStyles({width:this.menu_width});}
if(typeof props.event_type!='undefined'){this.events=props.event_type;}
else{this.InitializeSubProperties(this.events,props,"events",SKMenuOptions.events.DEFAULT);}
if(typeof props.behavior_type!='undefined'){this.behaviors=props.behavior_type;}
else{this.InitializeProperty(this.behaviors,props,"behaviors",SKMenuOptions.behaviors.DEFAULT);}
if(typeof props.timeout!='undefined'){this.timeout=props.timeout;}
else{this.InitializeSubProperties(this.timeout,props,"timeout",SKMenuOptions.timeouts.DEFAULT);}
this.InitializeSubProperties(this.slider,props,"slider",SKMenuOptions.slider.DEFAULT);this.InitializeSubProperties(this.callbacks,props,"callbacks",SKMenuOptions.callbacks.DEFAULT);this.InitializeProperty(this.scroll,props,"scroll",this.scroll);this.InitializeProperty(this.admin,props,"admin",this.admin);this.InitializeProperty(this.submenu_layout,props,"submenu_layout",this.submenu_layout);this.InitializeProperty(this.orientation,props,"orientation",this.orientation);this.InitializeProperty(this.style,props,"style",this.style);this.InitializeProperty(this.icon_width,props,"icon_width",this.icon_width);this.InitializeProperty(this.animation_props,props,"animation_props",SKAnimations.DEFAULT);this.dimensions=(typeof props.dimensions!='undefined')?props.dimensions:SKMenuOptions.dimensions.DEFAULT;this.holders=(typeof props.holders!='undefined')?props.holders:SKMenuOptions.holders.DEFAULT;this.helpers=(typeof props.helpers!='undefined')?props.helpers:{};},InitializeProperty:function(property,props,property_name,default_value){if(props&&typeof props[property_name]!='undefined'){property=props[property_name];}
else{property=default_value;}
this[property_name]=property;},InitializeSubProperties:function(property,props,property_name,default_value){var properties;if(props&&typeof props[property_name]!='undefined'){properties=props[property_name];for(var sub_property in default_value){if(typeof properties[sub_property]!='undefined'){property[sub_property]=properties[sub_property];}
else{property[sub_property]=default_value[sub_property];}}}
else{property=default_value;}
this[property_name]=property;},SetSubmenuPosition:function(item){if(this.orientation==VERTICAL&&this.submenu_layout==DROPDOWN_BETWEEN_ITEMS)
return;var sub_menu;if($(item.sub_menu_id)){sub_menu=new SKMenu($(item.sub_menu_id),item.root_obj);}else{sub_menu=item.SubMenu();}
if(typeof sub_menu!='undefined')
sub_menu.CalculatePositionRelativeToMainMenu(this.orientation,this.submenu_layout);},ResetSubitems:function(item){var sub_menu=item.SubMenu();if(typeof sub_menu!='undefined'){var items=sub_menu.Items();for(var i=0;i<items.length;i++){items[i].FlipImages(1);}}},traverse:function(callback){var id=this.element.id;this.menu=new SKMenu($(id),this);if(typeof callback!='undefined'){callback(id);}
if(this.callbacks["before_traverse"])
this.callbacks["before_traverse"](this);var menu_items=this.menu.Items();if(!menu_items||typeof menu_items=='undefined')return;for(var i=0;i<menu_items.length;i++){var menu_item=menu_items[i];SKEffectsFactory.TraverseMenuItem(menu_item);}
for(var i=0;i<menu_items.length;i++){var item=menu_items[i];SKEffectsFactory.ApplyMenuItemEffects(item,this);}
if(this.callbacks["after_traverse"]){this.callbacks["after_traverse"](this);}}});SKElement.GetChildrenByTag=function(element,tag,recursively){if(!element||typeof element=='undefined'||!tag||typeof tag=='undefined'||!element.childNodes||typeof element.childNodes=='undefined')return;var arrChildren=new Array();var arrTempChildren=element.childNodes;if(recursively)
arrTempChildren=SKElement.GetDOMChildren(element);for(var i=0;i<arrTempChildren.length;i++){var child=arrTempChildren[i];if(typeof child.tagName!='undefined'&&child.tagName.toUpperCase()==tag){arrChildren.push(child);}}
return arrChildren;}
SKElement.GetDOMChildren=function(oRoot){var arrChildren=[oRoot];var i=0;while(i<arrChildren.length){if(arrChildren[i].childNodes&&arrChildren[i].childNodes.length>0){for(var j=0;j<arrChildren[i].childNodes.length;j++)
arrChildren.push(arrChildren[i].childNodes[j])}
i++;}
return arrChildren;}
SKElement.ParentListElement=function(element){if(!element||typeof element=='undefined')return null;var parent;while(element.parentNode){parent=element.parentNode;if(typeof parent.tagName=='undefined')break;var tag_name=parent.tagName.toUpperCase();if(tag_name=="UL"||tag_name=="OL"||tag_name=="TABLE"){break;}
element=parent;}
element=parent;return element;}
SKElement.GetFirstElementByTag=function(element,tag){if(typeof element.id!='undefined'&&element.id!=''&&typeof hashFirstElementMap[element.id]!='undefined'&&typeof hashFirstElementMap[element.id][tag]!='undefined'){return hashFirstElementMap[element.id][tag];}
var iPointer=0;var arrChildNodes=[];arrChildNodes.push(element);while(iPointer<arrChildNodes.length){if(arrChildNodes[iPointer]&&arrChildNodes[iPointer].childNodes)
{arrTemp=arrChildNodes[iPointer].childNodes;for(var i=0;i<arrTemp.length;i++){if(typeof arrTemp[i].tagName!='undefined'&&arrTemp[i].tagName.toUpperCase()==tag){if(typeof hashFirstElementMap[element.id]=='undefined')
hashFirstElementMap[element.id]=[];hashFirstElementMap[element.id][tag]=arrTemp[i];return arrTemp[i];}else{arrChildNodes.push(arrTemp[i]);}}}
iPointer++;}}
SKElement.GetParentByTag=function(element,tag){if(!element||typeof element=='undefined')return;var parent;var found=false;while(element.parentNode){parent=element.parentNode;if(parent.tagName&&parent.tagName.toUpperCase()==tag){found=true;break;}
element=parent;}
var not_found;element=(found)?parent:not_found;return element;}
SKElement.GetParentByClassName=function(element,sClassName){var parent;var found=false;while(element.parentNode){parent=element.parentNode;if(parent.className&&parent.className.indexOf(sClassName)!=-1){found=true;break;}
element=parent;}
var not_found;element=(found)?parent:not_found;return element;}
SKElement.GetBorderWidth=function(element){var oBorderWidth=new Object();oBorderWidth.top=0;oBorderWidth.right=0;oBorderWidth.bottom=0;oBorderWidth.left=0;if(typeof element.getStyle=='undefined')
return null;sCSSAttributeValue=element.getStyle("border-width");if(!sCSSAttributeValue||typeof sCSSAttributeValue=='undefined')
return null;if(sCSSAttributeValue=='thin'||sCSSAttributeValue=='medium'||sCSSAttributeValue=='thick')
return null;var arrBorderWidth=new Array();arrBorderWidth=sCSSAttributeValue.split(' ');if(!arrBorderWidth||typeof arrBorderWidth=='undefined')
return null;switch(arrBorderWidth.length){case 1:oBorderWidth.top=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.right=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.bottom=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.left=SKUtils.SizeToNumber(arrBorderWidth[0]);break;case 2:oBorderWidth.top=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.right=SKUtils.SizeToNumber(arrBorderWidth[1]);oBorderWidth.bottom=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.left=SKUtils.SizeToNumber(arrBorderWidth[1]);break;case 3:oBorderWidth.top=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.right=SKUtils.SizeToNumber(arrBorderWidth[1]);oBorderWidth.bottom=SKUtils.SizeToNumber(arrBorderWidth[2]);oBorderWidth.left=SKUtils.SizeToNumber(arrBorderWidth[1]);break;case 4:oBorderWidth.top=SKUtils.SizeToNumber(arrBorderWidth[0]);oBorderWidth.right=SKUtils.SizeToNumber(arrBorderWidth[1]);oBorderWidth.bottom=SKUtils.SizeToNumber(arrBorderWidth[2]);oBorderWidth.left=SKUtils.SizeToNumber(arrBorderWidth[3]);break;default:return null;}
return oBorderWidth;}
SKElement.MoveChild=function(container,child){var container=$(container);container.appendChild($(child));}
SKElement.ContainsElementOfClass=function(element,class_name){if(typeof element=='undefined'){return false;}
var children=element.childNodes;var result=false;for(var i=0;i<children.length;i++){var child=children[i];if(typeof child.tagName!='undefined'){if($(child).className.indexOf(class_name)!=-1){return true;}
result=SKElement.ContainsElementOfClass(child,class_name);if(result==true){return true;}}}
return false;}
SKUtils.SizeToNumber=function(size){if(typeof size=='undefined'||size==null)return 0;var result=size;if(typeof size=='string'){result=size.replace("px","");result.replace("pt","");}
result-=0;return result;}
SKUtils.SetOnLoad=function(callback){var old_func=null;if(typeof window.onload=='function'){old_func=window.onload;window.onload=function(){old_func();callback();}}
else{window.onload=function(){callback();}};}
SKUtils.ExtendMethod=function(object,method,ext){var old=object[method];object[method]=function(arg){if(old){object._=old;object._(arg);}
object._=ext;object._(arg);}}
SKUtils.PrepareMenuContainer=function(container_id,submenu_layout){var class_name=container_id+"_"+submenu_layout;if(!$(container_id)){container_element=document.createElement("div");container_element.id=container_id;var body=document.getElementsByTagName("body")[0]
body.insertBefore(container_element,body.firstChild)}
$(container_id).addClass(class_name);$(container_id).removeClass(container_id+"_"+submenu_layout);}
SKUtils.RemoveElement=function(container_id){if($(container_id)){var parent_element=$(container_id).parentNode;parent_element.removeChild($(container_id))}}
SKUtils.MergeHashes=function(org_hash,new_hash){var result=$H(org_hash);return result.combine($H(new_hash));}
SKUtils.GetCurrentPageUrl=function(){return document.location.href;}


var EFFECTS_FACTORY_CACHE=[];function SKEffectsFactory(){this.timeout=100;this.handles={};this.visible_items={};this.menu_items;};var SKEffectsFactoryObj=new SKEffectsFactory();SKEffectsFactory.Synchronization={};SKEffectsFactory.SubSynchronization={};function SKMenuBehaviors(){};SKMenuBehaviors.behaviors={};SKMenuBehaviors.events={};SKMenuBehaviors.timeouts={};SKMenuBehaviors.types={};SKEffectsFactory.cm=0;SKEffectsFactory.hide=0;SKEffectsFactory.Hide=function(item,callback,timeout){if(typeof item=="undefined")return;var id=item.element.id;if(typeof callback=="undefined"){callback=SKMenuBehaviors.types.DEFAULT["onhide"];}
this.CancelTimeout(id)
if(item.IsSubItem()||timeout==0){callback(item);}
else{SKEffectsFactoryObj.handles[id]=window.setTimeout(function(){callback(item);},timeout);}}
SKEffectsFactory.ForceHide=function(menu_item){if(typeof menu_item=="undefined")return;var id=menu_item.element.id;var root_obj=menu_item.root_obj;var callback=root_obj.behaviors["onhide"];var timeout=root_obj.timeout.rollover_next;this.CancelTimeout(id);SKEffectsFactoryObj.handles[id]=window.setTimeout(function(){callback(menu_item);},timeout);}
SKEffectsFactory.KeepVisible=function(item){if(typeof item=="undefined")return;var id=item.element.id;this.CancelTimeout(id);}
SKEffectsFactory.CancelTimeout=function(id){if(typeof id=="undefined")return;if(typeof SKEffectsFactoryObj.handles[id]!='undefined'&&SKEffectsFactoryObj.handles[id]){window.clearTimeout(SKEffectsFactoryObj.handles[id]);SKEffectsFactoryObj.handles[id]=null;}}
SKEffectsFactory.KeepVisibleMany=function(items){if(typeof items=="undefined")return;for(var i=0;i<items.length;i++){var item=items[i];SKEffectsFactory.KeepVisible(item);}}
SKEffectsFactory.ApplyMenuItemEffects=function(menu_item){var list_item=menu_item.element;var root_obj=menu_item.root_obj;var sub_list;if($(menu_item.sub_menu_id)){sub_list=new SKMenu($(menu_item.sub_menu_id),menu_item.root_obj);}else{sub_list=menu_item.SubMenu();}
var menu_obj=sub_list;var callback_show=root_obj.behaviors["onshow"];var callback_hide=root_obj.behaviors["onhide"];var callback_click=root_obj.behaviors["onclick"];var timeout_show=root_obj.timeout.show;var timeout_hide=root_obj.timeout.hide;var timeout_click=root_obj.timeout.click;if(menu_item.IsSubItem()){timeout_show=root_obj.timeout.show_sub;timeout_hide=root_obj.timeout.hide_sub;}
else{if(typeof root_obj.timeout.hide_no_sub!='undefined'&&typeof sub_list=='undefined'){timeout_hide=root_obj.timeout.hide_no_sub;}}
var behavior={};behavior.show={'show':[],'hide':[]};behavior.hide={'show':[],'hide':[]};behavior.click={'click':[]};if(typeof sub_list!="undefined"){behavior.show['show'].push(sub_list);behavior.click['click'].push(sub_list);}
var parent_menu=menu_item.ParentMenu();if(typeof parent_menu!="undefined"){behavior.show['show'].push(parent_menu);behavior.click['click'].push(parent_menu);}
behavior.hide['hide'].push(menu_item);var event={};event.show=function(){SKEffectsFactory.hide=0;var id=menu_item.element.id;var menu_obj;if($(menu_item.sub_menu_id)){menu_obj=new SKMenu($(menu_item.sub_menu_id),menu_item.root_obj);}else{menu_obj=menu_item.SubMenu();}
if(!menu_item.IsSubItem()&&menu_item.SubSynchronized()){return;}
else{menu_item.SubSynchronized(true);}
if(typeof SKEffectsFactoryObj.handles[id]!='undefined'){window.clearTimeout(SKEffectsFactoryObj.handles[id]);}
var parent_item=menu_item.ParentMenuItem();if(typeof parent_item!='undefined'){window.clearTimeout(SKEffectsFactoryObj.handles[parent_item.element.id]);}
SKEffectsFactoryObj.handles[id]=window.setTimeout(function(){callback_show(menu_item);SKEffectsFactory.KeepVisibleMany(behavior.show['show']);},timeout_show);};event.hide=function(){SKEffectsFactory.hide=1;var to=timeout_hide;if(SKEffectsFactory.cm>0){SKEffectsFactory.CMDelayHide(arguments.callee);return;}
if(menu_item.IsSubItem()){menu_item.SubSynchronized(true,1);}
else{if(SKEffectsFactory.SubSynchronization[menu_item.element.id]>=1){SKEffectsFactory.SubSynchronization[menu_item.element.id]=2;}}
SKEffectsFactory.Hide(menu_item,callback_hide,timeout_hide);};event.click=function(e){var event_obj;if(e.target){event_obj=e.target;}else{event_obj=e.srcElement;}
var event_obj_parent_anchor;if(event_obj&&typeof event_obj!='undefined'){if(event_obj.tagName.toUpperCase()=='A'){event_obj_parent_anchor=event_obj;}else{event_obj_parent_anchor=SKElement.GetParentByTag(event_obj,'A');}}
if(event_obj_parent_anchor&&typeof event_obj_parent_anchor!='undefined'){if(typeof event_obj_parent_anchor.className!='undefined'&&event_obj_parent_anchor.className.indexOf('subItem')!=-1)
return;}
var id=menu_item.element.id;var menu_obj;if($(menu_item.sub_menu_id)){menu_obj=new SKMenu($(menu_item.sub_menu_id),menu_item.root_obj);}else{menu_obj=menu_item.SubMenu();}
if(!menu_item.IsSubItem()&&menu_item.SubSynchronized()){return;}
else{menu_item.SubSynchronized(true);}
if(typeof SKEffectsFactoryObj.handles[id]!='undefined'){window.clearTimeout(SKEffectsFactoryObj.handles[id]);}
var parent_item=menu_item.ParentMenuItem();if(typeof parent_item!='undefined'){window.clearTimeout(SKEffectsFactoryObj.handles[parent_item.element.id]);}
SKEffectsFactoryObj.handles[id]=window.setTimeout(function(){callback_click(menu_item);SKEffectsFactory.KeepVisibleMany(behavior.click['click']);},timeout_click);}
var event_conf=root_obj.events;SKEffectsFactory.AddEventListeners(list_item,event_conf,event);}
SKEffectsFactory.AddEventListeners=function(element,event_conf,event){for(var event_name in event_conf){var callback_name=event_conf[event_name];if(typeof callback_name!='undefined'){$(element.id).addEvent(event_name,event[callback_name]);}}}
SKEffectsFactory.GenerateItemID=function(item){if(!$defined(item.id)||item.id==""){item.id="item_"+(new Date()).getTime()+"_"+Math.round(10000*Math.random());}}
SKEffectsFactory.TraverseMenuItem=function(menu_item){var parent_id=menu_item.parent_id;var count=menu_item.position;var root_obj=menu_item.root_obj;SKEffectsFactory.GenerateItemID(menu_item.element);var contents=menu_item.GetContentsElement();if(typeof root_obj.holders.item!='undefined'&&typeof contents!='undefined'){SKEffectsFactory.GenerateHolders(contents,root_obj.holders.item)}
var sub_menu=menu_item.SubMenu();if(typeof sub_menu!='undefined'){SKEffectsFactory.GenerateItemID(sub_menu.element);menu_item.sub_menu_id=sub_menu.element.id;if(!EFFECTS_FACTORY_CACHE[sub_menu.element.id])
EFFECTS_FACTORY_CACHE[sub_menu.element.id]=new Object();if(!EFFECTS_FACTORY_CACHE[sub_menu.element.id].width)
EFFECTS_FACTORY_CACHE[sub_menu.element.id].width=0;if(!EFFECTS_FACTORY_CACHE[sub_menu.element.id].height)
EFFECTS_FACTORY_CACHE[sub_menu.element.id].height=0;if(typeof root_obj.holders.submenu!='undefined'){SKEffectsFactory.GenerateHolders(sub_menu.element,root_obj.holders.submenu)}
var holder=sub_menu.GetHolder();holder.addEvent('click',function(event){event.stopPropagation();});var sub_items=sub_menu.Items();if(typeof contents!='undefined'){for(var j=0;j<sub_items.length;j++){var sub_item=sub_items[j];SKEffectsFactory.GenerateItemID(sub_item.element);contents=sub_item.GetContentsElement();if(!contents)continue;var oDummy=contents.cloneNode(true);oDummy.className=(root_obj.submenu_layout==0)?contents.className+'__dummy_0':contents.className+'__dummy_1';document.body.appendChild(oDummy)
var iWidth=oDummy.offsetWidth;var iHeight=oDummy.offsetHeight;if(iHeight==0)
iHeight=root_obj.dimensions.dft_si_height;if(root_obj.submenu_layout==0){EFFECTS_FACTORY_CACHE[sub_menu.element.id].width+=iWidth+root_obj.dimensions.menu_padding;EFFECTS_FACTORY_CACHE[sub_menu.element.id].height=(iHeight>EFFECTS_FACTORY_CACHE[sub_menu.element.id].height)?iHeight:EFFECTS_FACTORY_CACHE[sub_menu.element.id].height;}else{iWidth+=root_obj.dimensions.menu_padding;EFFECTS_FACTORY_CACHE[sub_menu.element.id].width=(iWidth>EFFECTS_FACTORY_CACHE[sub_menu.element.id].width)?iWidth:EFFECTS_FACTORY_CACHE[sub_menu.element.id].width;EFFECTS_FACTORY_CACHE[sub_menu.element.id].height+=iHeight+root_obj.dimensions.menu_padding/2;}
oDummy=document.body.removeChild(oDummy);SKEffectsFactory.ApplyMenuItemEffects(sub_item,this);}}
if(typeof menu_item.root_obj.animation_props!='undefined'){ITEMS_FX[menu_item.element.id]=menu_item.root_obj.animation_props.effect(menu_item,menu_item.root_obj.animation_props.options);menu_item.root_obj.animation_props.reset(ITEMS_FX[menu_item.element.id]);}}}
SKEffectsFactory.AddScrollLayersItems=function(menu_item){if(!menu_item.FirstLink())return;var link_element=menu_item.FirstLink();var window_width=$(link_element).getStyle("width");window_width=SKUtils.SizeToNumber(window_width);var real_width=window_width;var real_height=$(menu_item.element).getStyle("height");real_height=SKUtils.SizeToNumber(real_height);var anchor_element=menu_item.FirstLink();var layer=SKElement.GetFirstElementByTag($(link_element),"SPAN");if(typeof layer!='undefined'){window_width=$(layer).getStyle('width');window_width=SKUtils.SizeToNumber(window_width);var second_layer=SKElement.GetFirstElementByTag($(layer),"SPAN");if(typeof second_layer!='undefined'){real_width=$(second_layer).getStyle("width");real_width=SKUtils.SizeToNumber(real_width);}}
if(typeof link_element!='undefined'&&real_width>window_width){var scroll_layer=SKElement.GetChildrenByTag(link_element,"SPAN");if(typeof scroll_layer!='undefined'&&typeof scroll_layer[0]!='undefined'){scroll_layer=scroll_layer[0];scroll_layer=SKElement.GetChildrenByTag(scroll_layer,"SPAN")[0];var slider_name=menu_item.element.id+"_slider";var timeout_wait=menu_item.root_obj.slider.wait;var slider_step=menu_item.root_obj.slider.step;SKSliders[slider_name]=new SKTwoWaySlider(scroll_layer,slider_name,{org_width:real_width,window_width:window_width,timeout_wait:timeout_wait,step:slider_step});}}}
SKEffectsFactory.GenerateHolders=function(element,holders_props){var parent_node=$(element).parentNode;var current_parent=parent_node
for(var i=0;i<holders_props.length;i++){var holder_props=holders_props[i];var holder_element=document.createElement(holder_props.tagName);for(var property in holder_props){var value=holder_props[property];switch(property)
{case"style":$(holder_element).setStyles(value);break;case"class":$(holder_element).addClass(holder_props[property]);break;}}
current_parent.appendChild(holder_element);current_parent=holder_element;}
current_parent.appendChild(element);}
SKEffectsFactory.CMOnDisplayCallbackOn=function(fh,obj){SKEffectsFactory.cm=1;SKEffectsFactory.DELAYED_HIDE=null;SKEffectsFactory.CancelTimeout(obj.id);var env=fh.getEnv(obj);if($defined(env)&&$defined(env.hl_rel_elements)){for(var i=0;i<env.hl_rel_elements;i++){SKEffectsFactory.CancelTimeout(env.hl_rel_elements[i]);}}}
SKEffectsFactory.CMOnDisplayCallbackOff=function(fh,obj){SKEffectsFactory.cm=0;if(SKEffectsFactory.DELAYED_HIDE!=null){SKEffectsFactory.DELAYED_HIDE();}}
SKEffectsFactory.CMDelayHide=function(f){SKEffectsFactory.DELAYED_HIDE=f;}
SKEffectsFactory.PlaceholdersHideCancel=function(meta,parent_id){SKEffectsFactory.cm=1;SKEffectsFactory.CancelTimeout(parent_id);}
SKEffectsFactory.PlaceholdersExecuteCancel=function(meta,parent_id){SKEffectsFactory.cm=0;if(SKEffectsFactory.DELAYED_HIDE!=null){SKEffectsFactory.DELAYED_HIDE();}}
SKEffectsFactory.SlideFinishedVisible=function(fh,obj){var visible=obj.parentNode.parentNode.get('visible')==0?false:true;return visible;}


SK.Actions.Freemona={};SK.Actions.Freemona.Page={};SK.Actions.Freemona.Page.editTmplOptionsCallback=function(meta,params,window_options){if(params&&params.edit_tmpl&&params.edit_tmpl=="$image_edit_tmpl"){return{window_options:{width:1060,height:720}};}
return{};}
SK.Actions.Freemona.Page.initPageImageCM=function(id){var cm_holder=$(id);var page_image=document.getElement('.pageImage');if($defined(page_image)){if(page_image.getComputedStyle('display')=="none"){var zero_footprint=cm_holder.getElement('div.sk-zero-footprint');if(Browser.Engine.trident4){zero_footprint.setStyle('height',30);}
var cm_target=new Element('div').grab(zero_footprint).wraps(page_image);}else{var cm_target=page_image;}
cm_target.setProperties({meta:cm_holder.get('meta'),env:cm_holder.get('env')});}
var dump=cm_holder.parentNode.removeChild(cm_holder);}


SKMenuOptions.callbacks.FM_DEFAULT={};SKMenuOptions.callbacks.FM_DEFAULT.after_traverse=function(main_menu){var items=main_menu.menu.Items();var layout=main_menu.layout;var parent_menu=main_menu.menu.element;var scroll=main_menu.scroll;var helpers=main_menu.helpers;var container_id="container_menu";SKUtils.PrepareMenuContainer(container_id,layout);for(var i=0;i<items.length;i++){var item=items[i];if(!SKElement.GetFirstElementByTag(item.element,'A'))continue;if(i==0)item.element.className+=FIRST_BUTTON_CLASS_NAME;if(i==items.length-1)item.element.className+=LAST_BUTTON_CLASS_NAME;if(SK__IsCurrentPage(item.internal_link)&&item.state_marker_element.className!=CURRENT_CLASS_NAME)
{item.state_marker_element.className=CURRENT_CLASS_NAME;}
var parent_node_id=item.element.retrieve('node_id');var selected_image_was_set=false;var sub_menu=item.SubMenu();if(typeof sub_menu!='undefined'){var subitems=sub_menu.Items();for(var j=0;j<subitems.length;j++){var subitem=subitems[j];var node_id=subitem.element.retrieve('node_id');if(!SKElement.GetFirstElementByTag(subitem.element,'A'))continue;if(SK__IsCurrentPage(subitem.internal_link))
{if(item.state_marker_element.className!=CURRENT_CLASS_NAME)
item.state_marker_element.className=CURRENT_CLASS_NAME;if(subitem.state_marker_element.className!=CURRENT_SUBITEM_CLASS_NAME)
subitem.state_marker_element.className=CURRENT_SUBITEM_CLASS_NAME;if(parent_node_id){SetSelectedImage('mi'+node_id+'__over','mi'+node_id+'__out','mi'+node_id+'__sel',subitem.internal_link);SetSelectedImage('mi'+parent_node_id+'__over','mi'+parent_node_id+'__out','mi'+parent_node_id+'__sel',subitem.internal_link);selected_image_was_set=true;}}else{SetSelectedImage('mi'+node_id+'__over','mi'+node_id+'__out','mi'+node_id+'__sel',subitem.internal_link);}
if(j==0)subitem.element.className+=FIRST_BUTTON_CLASS_NAME;if(j==subitems.length-1)subitem.element.className+=LAST_BUTTON_CLASS_NAME;}
if(main_menu.orientation==VERTICAL&&main_menu.submenu_layout==DROPDOWN_BETWEEN_ITEMS)
{var holder=sub_menu.GetHolder();if(item.state_marker_element.className==CURRENT_CLASS_NAME&&holder){$(holder).setStyles({'display':'block','visibility':'visible','position':'static','margin':'0px'});SKMenuOptions.behaviors.CLICK.onclick(item,true);}else{$(holder).setStyles({'display':'block'});}}else if(main_menu.orientation==HORIZONTAL&&main_menu.submenu_layout==DROPDOWN_BELOW_MAIN_ITEMS){var holder=sub_menu.GetHolder();var height=$(holder).getCoordinates().height;if(parseInt(height)>0){var subitems=sub_menu.Items();var new_height=parseInt(height)+(subitems.length+1)*10;holder.setStyle('height',new_height);}}}
if(parent_node_id&&!selected_image_was_set){SetSelectedImage('mi'+parent_node_id+'__over','mi'+parent_node_id+'__out','mi'+parent_node_id+'__sel',item.internal_link);}}
SKUtils.RemoveElement(container_id);main_menu.menu.element.setStyle('display','');}
SKMenuOptions.timeouts.FM_HORIZONTAL_SUBMENU={show:50,hide:1000,hide_no_sub:100,show_sub:0,hide_sub:0,rollover_next:50,click:0};SKMenuOptions.dimensions.FM_DEFAULT={first_level:{visible_window_width:140},subitems:{visible_window_width:200,stretch_increment:100},menu_padding:0,dft_si_height:25,vertical_item_width:160,vertical_item_height:30}
SKDesigns.FM_HorizontalMenu_VerticalSubmenu={dimensions:SKMenuOptions.dimensions.FM_DEFAULT,callbacks:SKMenuOptions.callbacks.FM_DEFAULT}
SKDesigns.FM_HorizontalMenu_HorizontalSubmenu={timeout:SKMenuOptions.timeouts.FM_HORIZONTAL_SUBMENU,dimensions:SKMenuOptions.dimensions.FM_DEFAULT,callbacks:SKMenuOptions.callbacks.FM_DEFAULT}
SKDesigns.FM_VerticalMenu_SubmenuOnClick={event_type:SKMenuOptions.events.CLICK,behaviors:SKMenuOptions.behaviors.CLICK,dimensions:SKMenuOptions.dimensions.FM_DEFAULT,callbacks:SKMenuOptions.callbacks.FM_DEFAULT}
SKDesigns.FM_VerticalMenu_SubmenuOnMover={dimensions:SKMenuOptions.dimensions.FM_DEFAULT,callbacks:SKMenuOptions.callbacks.FM_DEFAULT}


var SECTION_PADDING=20;var SLIDE_ANIMATION=0;var FADE_ANIMATION=1;var DEFAULT_ANIMATION=2;var FREEMONA_COLORS=new Array({color:"#00aeff"});


var fm_mnav=null;var fm_sec_menu=null;var fm_menu_design_map=new Array();fm_menu_design_map[STRIPE_BELOW_MAIN_ITEMS]=SKDesigns.FM_HorizontalMenu_HorizontalSubmenu;fm_menu_design_map[DROPDOWN_BELOW_MAIN_ITEMS]=SKDesigns.FM_HorizontalMenu_VerticalSubmenu;fm_menu_design_map[DROPDOWN_BETWEEN_ITEMS]=SKDesigns.FM_VerticalMenu_SubmenuOnClick;fm_menu_design_map[DROPDOWN_AT_RIGHT]=SKDesigns.FM_VerticalMenu_SubmenuOnMover;var fm_menu_animation_props_map=new Array();fm_menu_animation_props_map[STRIPE_BELOW_MAIN_ITEMS]=new Array();fm_menu_animation_props_map[STRIPE_BELOW_MAIN_ITEMS][SLIDE_ANIMATION]=SKAnimations.SLIDE;fm_menu_animation_props_map[STRIPE_BELOW_MAIN_ITEMS][FADE_ANIMATION]=SKAnimations.FADE;fm_menu_animation_props_map[STRIPE_BELOW_MAIN_ITEMS][DEFAULT_ANIMATION]=SKAnimations.DEFAULT;fm_menu_animation_props_map[DROPDOWN_BELOW_MAIN_ITEMS]=new Array();fm_menu_animation_props_map[DROPDOWN_BELOW_MAIN_ITEMS][SLIDE_ANIMATION]=SKAnimations.SLIDE;fm_menu_animation_props_map[DROPDOWN_BELOW_MAIN_ITEMS][FADE_ANIMATION]=SKAnimations.FADE;fm_menu_animation_props_map[DROPDOWN_BELOW_MAIN_ITEMS][DEFAULT_ANIMATION]=SKAnimations.DEFAULT;fm_menu_animation_props_map[DROPDOWN_BETWEEN_ITEMS]=new Array();fm_menu_animation_props_map[DROPDOWN_BETWEEN_ITEMS][SLIDE_ANIMATION]=SKAnimations.SLIDE_DOWN;fm_menu_animation_props_map[DROPDOWN_BETWEEN_ITEMS][FADE_ANIMATION]=SKAnimations.FADE;fm_menu_animation_props_map[DROPDOWN_BETWEEN_ITEMS][DEFAULT_ANIMATION]=SKAnimations.DEFAULT;fm_menu_animation_props_map[DROPDOWN_AT_RIGHT]=new Array();fm_menu_animation_props_map[DROPDOWN_AT_RIGHT][SLIDE_ANIMATION]=SKAnimations.SLIDE_HORIZONTAL;fm_menu_animation_props_map[DROPDOWN_AT_RIGHT][FADE_ANIMATION]=SKAnimations.FADE;fm_menu_animation_props_map[DROPDOWN_AT_RIGHT][DEFAULT_ANIMATION]=SKAnimations.DEFAULT;function LoadMainMenu(menu_orientation,menu_style,submenu_layout,submenu_animation,admin){if($('fm_menu')){var props={design:fm_menu_design_map[submenu_layout],admin:admin,submenu_layout:submenu_layout,orientation:menu_orientation,style:menu_style,scroll:false,animation_props:fm_menu_animation_props_map[submenu_layout][submenu_animation]};if(submenu_animation==DEFAULT_ANIMATION&&menu_orientation==VERTICAL){props.holders=SKMenuOptions.holders.NOANIMATION;}
fm_mnav=new SKMainMenu("fm_menu",props);fm_mnav.traverse();}}
function LoadSecondaryMenu(menu_orientation,admin){var design;if(menu_orientation==HORIZONTAL){design=SKDesigns.FM_HorizontalMenu_VerticalSubmenu;}else{design=SKDesigns.FM_VerticalMenu_SubmenuOnClick;}
if($('fm_sec_menu')){fm_sec_menu=new SKMainMenu("fm_sec_menu",{design:design,admin:admin,orientation:menu_orientation,scroll:false});fm_sec_menu.traverse();}}
function SetSelectedImage(sImgOverID,sImgOutID,sImgSelectedID,sInternalLink){var oImgOver=$(sImgOverID);var oImgOut=$(sImgOutID);var oImgSelected=$(sImgSelectedID);var oAvailableNode=$pick(oImgSelected,oImgOver,oImgOut,null);var oTextNode=null;if(oAvailableNode){var children=oAvailableNode.parentNode.childNodes;for(var i=0;i<children.length;i++){if($type(children[i])=='textnode'){oTextNode=children[i];break;}}}
var arrRemoveElements=[oImgOver,oImgOut,oImgSelected,oTextNode];if(SK__IsCurrentPage(sInternalLink)){if(oImgSelected){oImgSelected.style.display='block';arrRemoveElements.erase(oImgSelected);}else if(oImgOver){oImgOver.style.display='block';arrRemoveElements.erase(oImgOver);}else if(oImgOut){oImgOut.style.display='block';arrRemoveElements.erase(oImgOut);}else{arrRemoveElements.erase(oTextNode);}}else{if(oImgOut){arrRemoveElements.erase(oImgOut);if(oImgOver){arrRemoveElements.erase(oImgOver);}}else{arrRemoveElements.erase(oTextNode);}
if(oImgOver){arrRemoveElements.erase(oImgOver);}}
arrRemoveElements.each(function(e){if(e)e.parentNode.removeChild(e);});}
SK.Actions.Freemona.MainMenu={};SK.Actions.Freemona.MainMenu.editTmplOptionsCallback=function(meta,params,window_options){return{params:{orientation:SK.Singletons.env.get('freemona').main_menu.orientation,PageLayout:SK.Singletons.env.get('freemona').main_menu.page_layout}};}
SK.Actions.Freemona.MainMenuItem={};SK.Actions.Freemona.MainMenuItem.editTmplOptionsCallback=function(meta,params,window_options){return{window_options:{width:750,height:680},params:{orientation:SK.Singletons.env.get('freemona').main_menu.orientation}};}
SK.Actions.Freemona.SecondaryMenu={};SK.Actions.Freemona.SecondaryMenu.editTmplOptionsCallback=function(meta,params,window_options){return{params:{orientation:SK.Singletons.env.get('freemona').secondary_menu.orientation,PageLayout:SK.Singletons.env.get('freemona').secondary_menu.page_layout}};}
SK.Actions.Freemona.SecondaryMenuItem={};SK.Actions.Freemona.SecondaryMenuItem.editTmplOptionsCallback=function(meta,params,window_options){return{window_options:{width:750,height:680},params:{orientation:SK.Singletons.env.get('freemona').secondary_menu.orientation}};}
SK.Actions.Freemona.SubMenuItem={editTmplOptionsCallback:function(meta,params,window_options){return{window_options:{width:750,height:680}};}}
SK.Actions.Freemona.BottomMenuItem={editTmplOptionsCallback:function(meta,params,window_options){return{window_options:{width:750,height:680}};}}
SK.Actions.Freemona.TopMenuItem={editTmplOptionsCallback:function(meta,params,window_options){return{window_options:{width:750,height:680}};}}


function LoadStyles(sStyleDefinitions){document.write('<style type="text/css">'+sStyleDefinitions+'</style>');}
if(typeof(SK)=='undefined'){SK={};}
if(typeof(SK.Actions)=='undefined'){SK.Actions={};}
if(typeof(SK.Actions.Freemona)=='undefined'){SK.Actions.Freemona={};}
SK.Actions.Freemona.showHideEmptySharedPanel=function(action){var wrapper=$$('#AREA__SHARED_PANEL .sharedElementContentWrapper');if(wrapper.length==1){var wrapper_children=wrapper[0].getChildren();if(wrapper_children.length==0||(wrapper_children.length==1&&wrapper_children[0].hasClass('sk-obj-placeholder'))){var elements=$$('#collapsiblePanel_cell','#collapsiblePanel','#fm_shared_panel_button_cell','#fm_shared_panel_button','#fm_collapsible_panel_button_expand','#fm_collapsible_panel_button_collapse');if(action=='hide'){elements.hide();}else{elements.show();}}}}
SK.Actions.Freemona.showHideEmptyTopNavigation=function(action){if($$('.miTopLink').length==0){var elements=$$('#fm_header_menu_cell','#fm_header_menu','#AREA__TOP_NAV_AREA','#top_menu_wrapper');if(action=='hide'){elements.hide();}else{elements.show();}}}
SK.Actions.Freemona.hideEmptySharedPanel=function(){SK.Actions.Freemona.showHideEmptySharedPanel('hide');}
SK.Actions.Freemona.hideEmptyTopNavigation=function(){SK.Actions.Freemona.showHideEmptyTopNavigation('hide');}
if(typeof(SK.UI)=='undefined'){SK.UI={};}
if(typeof(SK.UI.Preview)!='undefined'){SK.UI.Preview.addEvents({onEnable:SK.Actions.Freemona.showHideEmptySharedPanel.pass('hide'),onDisable:SK.Actions.Freemona.showHideEmptySharedPanel.pass('show')});SK.UI.Preview.addEvents({onEnable:SK.Actions.Freemona.showHideEmptyTopNavigation.pass('hide'),onDisable:SK.Actions.Freemona.showHideEmptyTopNavigation.pass('show')});}


function ApplyBorderSideImages(oProps){if(!oProps)return;var oObject=null;var sTopLeftImageSrc=null;var sTopImageSrc=null;var sTopRightImageSrc=null;var sLeftImageSrc=null;var sRightImageSrc=null;var sBottomLeftImageSrc=null;var sBottomImageSrc=null;var sBottomRightImageSrc=null;if(oProps.object)oObject=oProps.object;if(oProps.top_left_image)sTopLeftImageSrc=oProps.top_left_image;if(oProps.top_image)sTopImageSrc=oProps.top_image;if(oProps.top_right_image)sTopRightImageSrc=oProps.top_right_image;if(oProps.left_image)sLeftImageSrc=oProps.left_image;if(oProps.right_image)sRightImageSrc=oProps.right_image;if(oProps.bottom_left_image)sBottomLeftImageSrc=oProps.bottom_left_image
if(oProps.bottom_image)sBottomImageSrc=oProps.bottom_image;if(oProps.bottom_right_image)sBottomRightImageSrc=oProps.bottom_right_image;var oParentNode=oObject.parentNode;var oWrapper0=document.createElement('DIV');var oWrapper1=document.createElement('DIV');var oWrapper2=document.createElement('DIV');var oWrapper3=document.createElement('DIV');var oWrapper4=document.createElement('DIV');var oWrapper5=document.createElement('DIV');var oWrapper6=document.createElement('DIV');var oWrapper7=document.createElement('DIV');oWrapper0.id='wrapper_layer_0';oWrapper1.id='wrapper_layer_1';oWrapper2.id='wrapper_layer_2';oWrapper3.id='wrapper_layer_3';oWrapper4.id='wrapper_layer_4';oWrapper5.id='wrapper_layer_5';oWrapper6.id='wrapper_layer_6';oWrapper7.id='wrapper_layer_7';oWrapper0.style.backgroundImage='url("'+sTopLeftImageSrc+'")';oWrapper1.style.backgroundImage='url("'+sTopImageSrc+'")';oWrapper2.style.backgroundImage='url("'+sTopRightImageSrc+'")';oWrapper3.style.backgroundImage='url("'+sLeftImageSrc+'")';oWrapper4.style.backgroundImage='url("'+sRightImageSrc+'")';oWrapper5.style.backgroundImage='url("'+sBottomLeftImageSrc+'")';oWrapper6.style.backgroundImage='url("'+sBottomImageSrc+'")';oWrapper7.style.backgroundImage='url("'+sBottomRightImageSrc+'")';oParentNode.appendChild(oWrapper0);oWrapper0.appendChild(oWrapper1);oWrapper1.appendChild(oWrapper2);oWrapper2.appendChild(oWrapper3);oWrapper3.appendChild(oWrapper4);oWrapper4.appendChild(oWrapper5);oWrapper5.appendChild(oWrapper6);oWrapper6.appendChild(oWrapper7);oWrapper7.appendChild(oObject);}
function RunDebugMode(){var sUrl=document.location.href;var oProps=new Object();var sProps=sUrl.substr(sUrl.indexOf('?')+1);var arrProps=sProps.split('&');for(var i=0;i<arrProps.length;i++){var arrPair=arrProps[i].split('=');oProps[arrPair[0]]=new String();oProps[arrPair[0]]=arrPair[1];}
if(oProps.template_alignment){if(oProps.template_alignment==1){$('fm_browser_cell').align='left';}else if(oProps.template_alignment==2){$('fm_browser_cell').align='right';}else{$('fm_browser_cell').align='center';}}
if(oProps.template_width){$('site_body_table').style.width=oProps.template_width;}
var arrFreemonaMenuClasses=$('fm_menu').className.split(' ');if(oProps.menu_style){for(var i=0;i<arrFreemonaMenuClasses.length;i++){if(arrFreemonaMenuClasses[i].indexOf('menuStyle')!=-1)
arrFreemonaMenuClasses[i]='menuStyle'+oProps.menu_style;}
$('menu_stylesheet').href='../0101.nccdn.net/Designs/Freemona/css/menu_type_'+oProps.menu_style+'.css';}
if(oProps.menu_alignment){for(var i=0;i<arrFreemonaMenuClasses.length;i++){if(arrFreemonaMenuClasses[i].indexOf('menuAlign')!=-1)
if(oProps.menu_alignment==1){arrFreemonaMenuClasses[i]='menuAlignCenter';$('fm_menu').align='center';}else if(oProps.menu_alignment==2){arrFreemonaMenuClasses[i]='menuAlignRight';$('fm_menu').align='right';}else{arrFreemonaMenuClasses[i]='menuAlignLeft';$('fm_menu').align='left';}}}
var sFreemonaMenuClass=arrFreemonaMenuClasses.join(' ');$('fm_menu_wrapper').className=$('fm_menu').className=sFreemonaMenuClass;if(oProps.menu_padding){if(oProps.menu_padding.indexOf('px')==-1){$('fm_mnav_cell').style.padding=oProps.menu_padding+'px';}else{$('fm_mnav_cell').style.padding=oProps.menu_padding;}}
if(oProps.menu_bckg){if(oProps.menu_bckg==1){$('fm_mnav_cell').style.backgroundImage='url("../img.nccdn.net/Tools/file_direct_link.html@node_id=266335")';$('fm_mnav_cell').style.backgroundColor='red';}}
if(oProps.open_submenu){if(oProps.open_submenu==1){ONLOAD_FUNCTIONS[ONLOAD_FUNCTIONS.length]='OpenFirstSubmenu();';}}}
function GetDOMChildren(oRoot){var arrChildren=[oRoot];if(oRoot.childNodes.length>0){for(var i=0;i<oRoot.childNodes.length;i++){var arrTempChildren=GetDOMChildren(oRoot.childNodes[i]);for(var j=0;j<arrTempChildren.length;j++){arrChildren.push(arrTempChildren[j]);}}}
return arrChildren;}
function HasClass(sSrcClassName,sStyleToCheck){var arrClassNames=sSrcClassName.split(" ");for(var i=0;i<arrClassNames.length;i++){if(arrClassNames[i]==sStyleToCheck)return true;}
return false;}
function OpenFirstSubmenu(){var arrChildren=GetDOMChildren($('fm_menu'));for(var i=0;i<arrChildren.length;i++){if(typeof arrChildren[i].className!='undefined'){if(HasClass(arrChildren[i].className,'effects_holder')){arrChildren[i].style.display='block';i=arrChildren.length;}}}}


if(!oGlobalMenuObjects){var oGlobalMenuObjects=new Object();var nMenuObjectsCount=0;}
function DynamicFlashMenu(oJSONStruct){this.oJSONData=new Object();this.nInstanceId=new Number();this.sInstanceRefference=new String();this.oSWFRefference=new Object();this.oSWFObject=new Object();this.Init=function(){nMenuObjectsCount++;this.nInstanceId=nMenuObjectsCount;this.nInstanceRefference='menuObject_'+this.nInstanceId;oGlobalMenuObjects[this.nInstanceRefference]=this;var sSWFReffName=this.oJSONData.holder_id+'_swf';this.oSWFObject=new SWFObject(this.oJSONData.swf_url,sSWFReffName,"500","500","8");this.oSWFObject.addParam("scale","noscale");this.oSWFObject.addParam("wmode","transparent");this.oSWFObject.addVariable('ExternalRefference',this.nInstanceRefference);this.oSWFObject.addVariable('curURL',window.location.href);}
this.Draw=function(){this.oSWFObject.write(this.oJSONData.holder_id);this.oSWFRefference=document.getElementById(this.oJSONData.holder_id+'_swf');}
this.Resize=function(nWidth,nHeight){var sWStr=new String(nWidth+"px");var sHStr=new String(nHeight+"px");this.oSWFRefference.style.height=sHStr;this.oSWFRefference.style.width=sWStr;}
this.GetJSON=function(){return this.oJSONData;}
this.oJSONData=oJSONStruct;this.Init();}


if(typeof SK=='undefined'){SK={};}
if(typeof SK.Actions=='undefined'){SK.Actions={};}
if(typeof SK.Actions.Freemona=='undefined'){SK.Actions.Freemona={};}
SK.Actions.Freemona.expandPanel=function(config){var panel=$(config.panel);var content=$(config.content);if(!panel||!content)return;var height=content.getSize().y;if(!panel.retrieve('initial_height')){panel.store('initial_height',panel.getSize().y);}
panel.set('morph',{duration:1000,transition:'quart:out'});panel.morph({height:height});}
SK.Actions.Freemona.collapsePanel=function(config){var panel=$(config.panel);var content=$(config.content);if(!panel||!content)return;panel.set('morph',{duration:1000,transition:'quart:in'});panel.morph({height:panel.retrieve('initial_height')});}
SK.Actions.Freemona.swapVisible=function(e1,e2){[e1,e2].each(function(e){e=$(e);if(!e)return;if(e.getStyle('display')=='none'){e.setStyle('display','block');}else{e.setStyle('display','none');}});}


function CssFontFace(){this.fontFamilies={};this.loadedFonts={};this.selectors=[];this.replacementType=false;this.setAvailableFonts=function(fonts_array){if(this.replacementType!==false){for(var i=0;i<fonts_array.length;i++){this.fontFamilies[fonts_array[i].family.toLowerCase()]={src:fonts_array[i].src[this.replacementType],name:fonts_array[i].family,local:fonts_array[i].local}
if(fonts_array[i].selectors!=undefined){for(var j=0;j<fonts_array[i].selectors.length;j++){var selector=fonts_array[i].selectors[j];this.detectFontFamily(selector,'font-family',fonts_array[i].family);}}}}};this.generateCss=function(){if(this.selectors.length==0){return'';}
switch(this.replacementType){case'otf':return this.generateOpenType();break;case'eot':return this.generateEmbeddedOpenType();break;}
return'';};this.generateOpenType=function(){var css_text='';for(var i=0;i<this.selectors.length;i++){var font_family=this.fontFamilies[this.selectors[i].font_family].name;if(this.loadedFonts[font_family]==undefined){css_text+='@import url("'+this.fontFamilies[this.selectors[i].font_family].src+'" );\n';this.loadedFonts[font_family]=true;}}
return css_text;};this.generateEmbeddedOpenType=function(){var css_text='';for(var i=0;i<this.selectors.length;i++){var font_family=this.fontFamilies[this.selectors[i].font_family].name;if(this.loadedFonts[font_family]==undefined){css_text+='@font-face {\n'+'font-family:"'+font_family+'";\n'+'src: url("'+this.fontFamilies[this.selectors[i].font_family].src+'" );\n'+'}\n';this.loadedFonts[font_family]=true;}}
return css_text;};this.detectFontFamily=function(selector,property,value){if(this.replacementType===false){return;}
if(property=='font-family'&&value){var font_family=value.split(/\s?,\s?/).shift().toLowerCase().replace(/'|"/g,'');if(this.fontFamilies[font_family]){this.selectors.push({font_family:font_family,selector:selector});}}};this.reset=function(){this.selectors=[];this.loadedFonts={};};this.detectImplementationType=function(){var b=navigator.userAgent.toLowerCase();version_string=(b.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,'0'])[1],version_array=version_string.split('.'),version='';for(var i=0;i<version_array.length;i++){var n=version_array[i];if(i==1){version+='.';}
version+=String(n);}
version=parseFloat(version);var browser={version:version,webkit:/webkit/.test(b),opera:/opera/.test(b),msie:/msie/.test(b)&&!/opera/.test(b),mozilla:/mozilla/.test(b)&&!/(compatible|webkit)/.test(b)};if(browser.msie&&browser.version==9){this.replacementType='otf';}else if(browser.msie){this.replacementType='eot';}else if(browser.mozilla&&browser.version>=1.91){this.replacementType='otf';}else if(browser.webkit&&browser.version>=525){this.replacementType='otf';}}
this.detectImplementationType();}


SK.FontFace=new Class({Extends:CssFontFace,initialize:function(fonts_array,cufon_src){this.cufonSrc=cufon_src;if(!this.replacementType){this.replacementType='cufon';}
this.setAvailableFonts(fonts_array);},applyFontFace:function(){if(this.replacementType=='cufon'){this.applyCufon();}else{this.loadStyles(this.generateCss());}},applyCufon:function(){this.loadJsOnDemand(this.cufonSrc);var cufon_data=[];for(var i=0;i<this.selectors.length;i++){var font_family=this.fontFamilies[this.selectors[i].font_family].local;if(this.loadedFonts[font_family]==undefined){this.loadJsOnDemand(this.fontFamilies[this.selectors[i].font_family].src);this.loadedFonts[font_family]=true;}
cufon_data.push({selector:this.selectors[i].selector,font_family:font_family})}
window.addEvent('load',function(){var selector,font_family,matches,regex=new RegExp('(#fm_mnav .cs[0-9]+ .fm(Sub)?)(Cptn)');if(typeof(SKMenuItem)=="function"){SKMenuItem.implement({RefreshSelected:function(){Cufon.refresh();}})}
for(var i=0;i<cufon_data.length;i++){selector=cufon_data[i].selector;font_family=cufon_data[i].font_family;matches=regex.exec(selector);if(matches){selector=matches[1]+'Btn';}
Cufon.replace(selector,{fontFamily:font_family,hover:true});}});},loadJsOnDemand:function(jsfile){document.write('<scr'+'ipt type="text/jav'+'ascr'+'ipt" src="'+jsfile+'"></scr'+'ipt>');},loadStyles:function(cssText){document.write('<style type="text/css">'+cssText+'</style>');}});

